ALTER TABLE persons ADD COLUMN nsis_ordered BOOLEAN NOT NULL DEFAULT  0;
ALTER TABLE persons ADD COLUMN nsis_admin BOOLEAN NOT NULL DEFAULT  0;
ALTER TABLE persons_aud ADD COlUMN nsis_ordered BOOLEAN NULL;
ALTER TABLE persons_aud ADD COlUMN nsis_admin BOOLEAN NULL;
