CREATE TABLE SESSION_IDP (
	PRIMARY_ID CHAR(36) NOT NULL,
	SESSION_ID CHAR(36) NOT NULL,
	CREATION_TIME BIGINT NOT NULL,
	LAST_ACCESS_TIME BIGINT NOT NULL,
	MAX_INACTIVE_INTERVAL INT NOT NULL,
	EXPIRY_TIME BIGINT NOT NULL,
	PRINCIPAL_NAME VARCHAR(100),

	CONSTRAINT SESSION_IDP_pk PRIMARY KEY (PRIMARY_ID)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;

CREATE UNIQUE INDEX SESSION_IDP_ix1 ON SESSION_IDP (SESSION_ID);
CREATE INDEX SESSION_IDP_ix2 ON SESSION_IDP (EXPIRY_TIME);
CREATE INDEX SESSION_IDP_ix3 ON SESSION_IDP (PRINCIPAL_NAME);

CREATE TABLE SESSION_IDP_ATTRIBUTES (
	SESSION_PRIMARY_ID CHAR(36) NOT NULL,
	ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
	ATTRIBUTE_BYTES BLOB NOT NULL,
	CONSTRAINT SESSION_IDP_ATTRIBUTES_pk PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
	CONSTRAINT SESSION_IDP_ATTRIBUTES_fk FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SESSION_IDP(PRIMARY_ID) ON DELETE CASCADE
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;

CREATE TABLE SESSION_UI (
        PRIMARY_ID CHAR(36) NOT NULL,
        SESSION_ID CHAR(36) NOT NULL,
        CREATION_TIME BIGINT NOT NULL,
        LAST_ACCESS_TIME BIGINT NOT NULL,
        MAX_INACTIVE_INTERVAL INT NOT NULL,
        EXPIRY_TIME BIGINT NOT NULL,
        PRINCIPAL_NAME VARCHAR(100),

        CONSTRAINT SESSION_UI_pk PRIMARY KEY (PRIMARY_ID)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;

CREATE UNIQUE INDEX SESSION_UI_ix1 ON SESSION_UI (SESSION_ID);
CREATE INDEX SESSION_UI_ix2 ON SESSION_UI (EXPIRY_TIME);
CREATE INDEX SESSION_UI_ix3 ON SESSION_UI (PRINCIPAL_NAME);

CREATE TABLE SESSION_UI_ATTRIBUTES (
        SESSION_PRIMARY_ID CHAR(36) NOT NULL,
        ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
        ATTRIBUTE_BYTES BLOB NOT NULL,
        CONSTRAINT SESSION_UI_ATTRIBUTES_pk PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
        CONSTRAINT SESSION_UI_ATTRIBUTES_fk FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SESSION_UI(PRIMARY_ID) ON DELETE CASCADE
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
